name: hourly-trends

on:
  schedule:
    - cron: "0 * * * *"   # 매시 정각 (UTC 기준)
  workflow_dispatch: {}   # 수동 실행 버튼

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # 리베이스/머지 대비

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run crawler
        env:
          GEO_LIST: "KR,US,JP"
          CATEGORY_LIST: "3"     # 3=Business → API에선 b
          HOURS: "4"
          HL: "ko"
          TZ: "-540"
        run: npm run crawl

      # 충돌 덜 나는 간단한 자동 커밋/푸시
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update: realtime trends (KST)"
          file_pattern: |
            data/latest.json
            data/json/*.json
